# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'boost_container' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for boost_container

end

target 'cocos_engine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cocos_engine

end

target 'sbb-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleSignIn'
  # Pods for sbb-mobile

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_OBJC_WEAK'] ||= 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.3'
        end
    end
end
